[package]
name = "rainbow_core"
version = "0.1.0"
authors = ["Stephen Sugden <me@stephensugden.com>"]

[[bench]]
name = "eval"
harness = false

[dependencies]
pest = "^1.0.3"
pest_derive = "^1.0.3"
serde = "^1.0.15"
serde_derive = "^1.0.15"
id_tree = "^1.2.0"

[dev-dependencies]
bencher = "0.1.5"